[package]
name = "view"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
pixels = "0.9"
winit = "0.26"
winit_input_helper = "0.12"

ray_tracing_utils = { path = "../ray_tracing_utils" }
